[workspace]
members = ["ext/polars"]

[patch.crates-io]
jsonpath_lib = { git = "https://github.com/ritchie46/jsonpath", rev = "24eaf0b4416edff38a4d1b6b17bc4b9f3f047b4b" }
magnus-macros = { git = "https://github.com/matsadler/magnus" }
rb-sys-env = { git = "https://github.com/oxidize-rb/rb-sys" }

[profile.release]
strip = true
