[package]
name = "polars"
version = "0.1.0"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.4"
serde_json = "1"

[dependencies.polars]
version = "0.25.1"
features = [
    "abs",
    "arange",
    "csv-file",
    "cum_agg",
    "diagonal_concat",
    "dot_product",
    "dtype-full",
    "dynamic_groupby",
    "fmt",
    "horizontal_concat",
    "interpolate",
    "ipc",
    "is_first",
    "is_in",
    "json",
    "lazy",
    "lazy_regex",
    "moment",
    "parquet",
    "partition_by",
    "product",
    "random",
    "repeat_by",
    "rolling_window",
    "round_series",
    "search_sorted",
    "semi_anti_join",
    "serde-lazy",
    "sign",
    "strings",
    "to_dummies",
    "top_k",
    "trigonometry",
    "unique_counts",
]
