[package]
name = "polars"
version = "0.2.0"
license = "MIT"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8"
magnus = "0.4"
polars-core = "0.26.1"
serde_json = "1"

[dependencies.polars]
version = "0.26.1"
features = [
    "abs",
    "arange",
    "arg_where",
    "asof_join",
    "avro",
    "concat_str",
    "cse",
    "csv-file",
    "cum_agg",
    "cumulative_eval",
    "dataframe_arithmetic",
    "date_offset",
    "diagonal_concat",
    "diff",
    "dot_product",
    "dtype-full",
    "dynamic_groupby",
    "ewma",
    "extract_jsonpath",
    "fmt",
    "horizontal_concat",
    "interpolate",
    "ipc",
    "is_first",
    "is_in",
    "json",
    "lazy",
    "lazy_regex",
    "list_eval",
    "list_to_struct",
    "log",
    "meta",
    "mode",
    "moment",
    "object",
    "parquet",
    "partition_by",
    "pct_change",
    "performant",
    "pivot",
    "product",
    "propagate_nans",
    "random",
    "rank",
    "reinterpret",
    "repeat_by",
    "rolling_window",
    "round_series",
    "row_hash",
    "search_sorted",
    "semi_anti_join",
    "serde-lazy",
    "sign",
    "string_encoding",
    "string_justify",
    "strings",
    "timezones",
    "to_dummies",
    "top_k",
    "trigonometry",
    "unique_counts",
]

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc = { version = "0.1", default-features = false }
